# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
# https://konfido.github.io/2019/03/16/hexo-wiki/
# Site
title: 别院牧志
subtitle: IMOYAO
description: 深深别院，潜潜牧志，一个 Python 开发者的个人wiki。
author: imoyao
email: immoyao@gmail.com
slogan: 就命运而言，休论公道。
keywords: 别院牧志, imoyao, idealyard, 张牧志, 牧志, Python, 编程, Python开发
#language: zh-Hans    # for next
language: zh-CN       # for material
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: /
root: /
#permalink: :year/:month/:day/:title/
permalink: wiki/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - '_posts/**/embed_page/**'
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: 'masantu.com'
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)

# see also:: https://github.com/YuyingWu/hexo-generator-index-plus
# see also:[是否有排序功能? · Issue #9 · zthxxx/hexo-theme-Wikitten](https://github.com/zthxxx/hexo-theme-Wikitten/issues/9)
#index_generator:
#  path: ''
#  per_page: 10
#  order_by: -date
index_generator_plus:
  path: ''
  per_page: 10

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Wikitten

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:imoyao/wiki.git
#  repo: https://github.com/imoyao/wiki.git

  branch: master
# Local Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 代码高亮方案https://github.com/ele828/hexo-prism-plugin
#prism_plugin:
#  mode: 'preprocess'    # realtime/preprocess
#  theme: 'hopscotch'
#  line_number: true    # default false

# Markdown
## https://github.com/chjj/marked
# markdown:
#   gfm: true
#   pedantic: false
#   sanitize: false
#   tables: true
#   breaks: false
#   smartLists: true
#   smartypants: true

# [hexojs/hexo-renderer-marked: Markdown renderer for Hexo](https://github.com/hexojs/hexo-renderer-marked)
marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: 0
  autolink: true
  sanitizeUrl: false
  headerIds: true
  lazyload: false
  prependRoot: false
  external_link:
    enable: true
    exclude: ['www.masantu.com','blog.masantu.com','masantu.com']
    nofollow: false

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# 链接添加 nofollow，https://github.com/hexojs/hexo-filter-nofollow
nofollow:
  enable: true
  field: site
  exclude:
    - 'www.masantu.com'
    - 'blog.masantu.com'
    - 'masantu.com'

sitemap:
  path: sitemap.xml

# https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 2
  wpm: 300

# https://github.com/printempw/hexo-hide-posts
# hexo-hide-posts
hide_posts:
  # Change the filter name to fit your need
  filter: hide
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: []
  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines
  noindex: true

# Generate categories from directory-tree
# Dependencies: https://github.com/xu-song/hexo-auto-category
# depth: the max_depth of directory-tree you want to generate, should > 0
auto_category:
 enable: true
 depth: